// =============================================
// ECOSPHERE — Species Database
// All playable flora and fauna definitions
// =============================================
import type { SpeciesDefinition } from '../../types';

export const SPECIES_DATABASE: SpeciesDefinition[] = [
  // =================== FLORA ===================
  {
    id: 'floating_algae',
    name: 'Floating Algae',
    type: 'plant',
    emoji: '🌿',
    description: 'Photosynthetic microcolonies that drift freely in the biodome air layer. Primary oxygen producers.',
    baseTraits: {
      heatResistance: 0.4,
      coldResistance: 0.3,
      uvResistance: 0.5,
      reproductionRate: 0.8,
      efficiency: 0.7,
      aggression: 0,
      size: 0.5,
      speed: 0.05,
      bioluminescent: false,
      mutationChance: 0.02,
      color: '#39ff14',
    },
    preferredTemp: [15, 35],
    preferredHumidity: [50, 90],
    preferredLight: [40, 90],
    preferredPH: [6, 8],
    dietType: 'photosynthetic',
    baseReproductionInterval: 60,
    color: '#39ff14',
    initialPopulation: 20,
    zone: 'aerial',
    canBeAdded: true,
  },
  {
    id: 'bio_moss',
    name: 'Bioluminescent Moss',
    type: 'plant',
    emoji: '✨',
    description: 'Glowing moss colonies that anchor to dome walls. Emits cyan light in darkness.',
    baseTraits: {
      heatResistance: 0.3,
      coldResistance: 0.6,
      uvResistance: 0.3,
      reproductionRate: 0.4,
      efficiency: 0.6,
      aggression: 0,
      size: 0.6,
      speed: 0,
      bioluminescent: true,
      mutationChance: 0.03,
      color: '#00ffa3',
    },
    preferredTemp: [5, 25],
    preferredHumidity: [60, 100],
    preferredLight: [0, 50],
    preferredPH: [5, 7],
    dietType: 'photosynthetic',
    baseReproductionInterval: 120,
    color: '#00ffa3',
    glowColor: '#00ffff',
    initialPopulation: 10,
    zone: 'surface',
    canBeAdded: true,
  },
  {
    id: 'air_fern',
    name: 'Air Fern',
    type: 'plant',
    emoji: '🌱',
    description: 'Feathery fronds that float mid-dome, absorbing moisture directly from the air.',
    baseTraits: {
      heatResistance: 0.5,
      coldResistance: 0.4,
      uvResistance: 0.4,
      reproductionRate: 0.5,
      efficiency: 0.8,
      aggression: 0,
      size: 0.8,
      speed: 0.02,
      bioluminescent: false,
      mutationChance: 0.015,
      color: '#7fff00',
    },
    preferredTemp: [20, 40],
    preferredHumidity: [30, 70],
    preferredLight: [50, 80],
    preferredPH: [5.5, 7.5],
    dietType: 'photosynthetic',
    baseReproductionInterval: 90,
    color: '#7fff00',
    initialPopulation: 8,
    zone: 'aerial',
    canBeAdded: true,
  },
  {
    id: 'anchor_vine',
    name: 'Anchor Vine',
    type: 'plant',
    emoji: '🌾',
    description: 'Dense vine networks that stabilize the dome interior, creating micro-habitats for fauna.',
    baseTraits: {
      heatResistance: 0.6,
      coldResistance: 0.5,
      uvResistance: 0.6,
      reproductionRate: 0.3,
      efficiency: 0.9,
      aggression: 0,
      size: 1.2,
      speed: 0,
      bioluminescent: false,
      mutationChance: 0.01,
      color: '#228b22',
    },
    preferredTemp: [10, 45],
    preferredHumidity: [40, 80],
    preferredLight: [30, 70],
    preferredPH: [6, 8.5],
    dietType: 'photosynthetic',
    baseReproductionInterval: 200,
    color: '#228b22',
    initialPopulation: 5,
    zone: 'surface',
    canBeAdded: true,
  },
  {
    id: 'crystal_fungus',
    name: 'Crystal Fungus',
    type: 'plant',
    emoji: '🍄',
    description: 'Crystalline decomposer networks that break down dead matter and release nutrients.',
    baseTraits: {
      heatResistance: 0.4,
      coldResistance: 0.7,
      uvResistance: 0.2,
      reproductionRate: 0.6,
      efficiency: 0.95,
      aggression: 0,
      size: 0.7,
      speed: 0,
      bioluminescent: true,
      mutationChance: 0.025,
      color: '#bf5af2',
    },
    preferredTemp: [-5, 20],
    preferredHumidity: [50, 100],
    preferredLight: [0, 30],
    preferredPH: [4, 6.5],
    dietType: 'decomposer',
    baseReproductionInterval: 150,
    color: '#bf5af2',
    glowColor: '#df9bf4',
    initialPopulation: 6,
    zone: 'surface',
    canBeAdded: true,
  },
  {
    id: 'spore_cloud',
    name: 'Spore Cloud',
    type: 'plant',
    emoji: '💨',
    description: 'Gaseous spore colonies that drift in air currents. Colonize new surfaces rapidly.',
    baseTraits: {
      heatResistance: 0.5,
      coldResistance: 0.5,
      uvResistance: 0.7,
      reproductionRate: 0.95,
      efficiency: 0.5,
      aggression: 0,
      size: 0.3,
      speed: 0.15,
      bioluminescent: false,
      mutationChance: 0.04,
      color: '#ffd700',
    },
    preferredTemp: [0, 50],
    preferredHumidity: [20, 80],
    preferredLight: [10, 100],
    preferredPH: [5, 9],
    dietType: 'photosynthetic',
    baseReproductionInterval: 40,
    color: '#ffd700',
    initialPopulation: 0,
    zone: 'aerial',
    canBeAdded: true,
  },

  // =================== FAUNA ===================
  {
    id: 'microbe',
    name: 'Microbe',
    type: 'microbe',
    emoji: '🦠',
    description: 'Fundamental decomposers. Process waste and dead matter into nutrients.',
    baseTraits: {
      heatResistance: 0.6,
      coldResistance: 0.5,
      uvResistance: 0.3,
      reproductionRate: 0.9,
      efficiency: 0.8,
      aggression: 0.1,
      size: 0.2,
      speed: 0.1,
      bioluminescent: false,
      mutationChance: 0.05,
      color: '#ffaa44',
    },
    preferredTemp: [10, 45],
    preferredHumidity: [40, 100],
    preferredLight: [0, 60],
    preferredPH: [4, 9],
    dietType: 'decomposer',
    prey: [],
    baseReproductionInterval: 30,
    color: '#ffaa44',
    initialPopulation: 30,
    zone: 'aquatic',
    canBeAdded: true,
  },
  {
    id: 'tardigrade',
    name: 'Floating Tardigrade',
    type: 'animal',
    emoji: '🐾',
    description: 'Near-indestructible micro-animals. Survive extreme conditions. Feed on algae and moss.',
    baseTraits: {
      heatResistance: 0.9,
      coldResistance: 0.95,
      uvResistance: 0.9,
      reproductionRate: 0.3,
      efficiency: 0.85,
      aggression: 0.1,
      size: 0.4,
      speed: 0.08,
      bioluminescent: false,
      mutationChance: 0.01,
      color: '#87ceeb',
    },
    preferredTemp: [-10, 50],
    preferredHumidity: [10, 100],
    preferredLight: [0, 100],
    preferredPH: [3, 11],
    dietType: 'herbivore',
    prey: ['floating_algae', 'bio_moss', 'spore_cloud'],
    baseReproductionInterval: 300,
    color: '#87ceeb',
    initialPopulation: 15,
    zone: 'aerial',
    canBeAdded: true,
  },
  {
    id: 'nano_insect',
    name: 'Nano Insect',
    type: 'animal',
    emoji: '🪲',
    description: 'Miniature arthropods that graze on algae colonies and pollinate air ferns.',
    baseTraits: {
      heatResistance: 0.5,
      coldResistance: 0.3,
      uvResistance: 0.4,
      reproductionRate: 0.7,
      efficiency: 0.6,
      aggression: 0.2,
      size: 0.5,
      speed: 0.35,
      bioluminescent: false,
      mutationChance: 0.03,
      color: '#ff6b35',
    },
    preferredTemp: [15, 40],
    preferredHumidity: [30, 80],
    preferredLight: [30, 90],
    preferredPH: [5.5, 8],
    dietType: 'herbivore',
    prey: ['floating_algae', 'air_fern', 'spore_cloud'],
    baseReproductionInterval: 80,
    color: '#ff6b35',
    initialPopulation: 12,
    zone: 'aerial',
    canBeAdded: true,
  },
  {
    id: 'pollinator_drone',
    name: 'Pollinator Drone',
    type: 'animal',
    emoji: '🐝',
    description: 'Highly efficient pollinators that boost plant reproduction rates significantly.',
    baseTraits: {
      heatResistance: 0.6,
      coldResistance: 0.4,
      uvResistance: 0.5,
      reproductionRate: 0.5,
      efficiency: 0.9,
      aggression: 0.05,
      size: 0.6,
      speed: 0.5,
      bioluminescent: true,
      mutationChance: 0.02,
      color: '#ffd700',
    },
    preferredTemp: [20, 38],
    preferredHumidity: [40, 75],
    preferredLight: [50, 100],
    preferredPH: [6, 8],
    dietType: 'herbivore',
    prey: ['floating_algae', 'spore_cloud'],
    baseReproductionInterval: 120,
    color: '#ffd700',
    glowColor: '#ffff88',
    initialPopulation: 8,
    zone: 'aerial',
    canBeAdded: true,
  },
  {
    id: 'bio_worm',
    name: 'Bio Worm',
    type: 'animal',
    emoji: '🪱',
    description: 'Burrowing decomposers that cycle nutrients back into the ecosystem.',
    baseTraits: {
      heatResistance: 0.4,
      coldResistance: 0.6,
      uvResistance: 0.2,
      reproductionRate: 0.65,
      efficiency: 0.85,
      aggression: 0.05,
      size: 0.7,
      speed: 0.12,
      bioluminescent: false,
      mutationChance: 0.02,
      color: '#c8a97e',
    },
    preferredTemp: [5, 30],
    preferredHumidity: [60, 100],
    preferredLight: [0, 30],
    preferredPH: [5.5, 7.5],
    dietType: 'decomposer',
    prey: [],
    baseReproductionInterval: 180,
    color: '#c8a97e',
    initialPopulation: 10,
    zone: 'surface',
    canBeAdded: true,
  },
  {
    id: 'hover_beetle',
    name: 'Hover Beetle',
    type: 'animal',
    emoji: '🪳',
    description: 'Apex micro-predators. Hunt nano insects and tardigrades. Metallic exoskeleton.',
    baseTraits: {
      heatResistance: 0.7,
      coldResistance: 0.5,
      uvResistance: 0.7,
      reproductionRate: 0.3,
      efficiency: 0.75,
      aggression: 0.8,
      size: 1.0,
      speed: 0.6,
      bioluminescent: false,
      mutationChance: 0.015,
      color: '#4169e1',
    },
    preferredTemp: [10, 50],
    preferredHumidity: [20, 70],
    preferredLight: [20, 80],
    preferredPH: [5, 8.5],
    dietType: 'carnivore',
    prey: ['nano_insect', 'tardigrade', 'pollinator_drone'],
    baseReproductionInterval: 400,
    color: '#4169e1',
    initialPopulation: 4,
    zone: 'aerial',
    canBeAdded: true,
  },
];

export const getSpeciesById = (id: string): SpeciesDefinition | undefined =>
  SPECIES_DATABASE.find(s => s.id === id);

export const getSpeciesByType = (type: SpeciesDefinition['type']): SpeciesDefinition[] =>
  SPECIES_DATABASE.filter(s => s.type === type);

export const PLANTS = getSpeciesByType('plant');
export const ANIMALS = getSpeciesByType('animal');
export const MICROBES = getSpeciesByType('microbe');
