// Mock data for RTDRCP portal — simulates live Firestore data

export const MOCK_INCIDENTS = [
  {
    incidentId: 'inc-001',
    incidentType: 'flood',
    rawDescription: 'Flood water rising rapidly. Family of 5 trapped on rooftop at Shivaji Nagar near water tank. Elderly person 75yr with mobility issues. Urgent boat rescue needed.',
    aiTriage: {
      severity: 'P1_critical',
      category: 'rescue',
      extractedLocation: 'Shivaji Nagar water tank junction',
      triageNotes: 'Immediate water rescue required. Elderly with mobility limitation elevates medical risk.',
      triageConfidence: 0.97,
    },
    location: { lat: 22.3072, lng: 73.1812, landmark: 'Shivaji Nagar water tank' },
    status: 'triaged',
    casualtyCount: 5,
    damageLevel: 'critical',
    createdAt: new Date(Date.now() - 18 * 60000).toISOString(),
  },
  {
    incidentId: 'inc-002',
    incidentType: 'collapse',
    rawDescription: 'Building partially collapsed at MG Road. Multiple people trapped. 3 confirmed injured, 2 unaccounted.',
    aiTriage: {
      severity: 'P1_critical',
      category: 'rescue',
      extractedLocation: 'MG Road, collapsed building',
      triageNotes: 'USAR team required immediately. Medical standby needed.',
      triageConfidence: 0.94,
    },
    location: { lat: 22.3190, lng: 73.1850, landmark: 'MG Road' },
    status: 'new',
    casualtyCount: 5,
    damageLevel: 'critical',
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    incidentId: 'inc-003',
    incidentType: 'medical',
    rawDescription: 'Pregnant woman in labor, no hospital access due to road flooding. Immediate medical assistance required at Sector 12.',
    aiTriage: {
      severity: 'P1_critical',
      category: 'medical',
      extractedLocation: 'Sector 12 residential area',
      triageNotes: 'Obstetric emergency. Ambulance or medical helicopter required.',
      triageConfidence: 0.99,
    },
    location: { lat: 22.3015, lng: 73.1920, landmark: 'Sector 12' },
    status: 'assigned',
    casualtyCount: 2,
    damageLevel: 'high',
    createdAt: new Date(Date.now() - 32 * 60000).toISOString(),
  },
  {
    incidentId: 'inc-004',
    incidentType: 'fire',
    rawDescription: 'Gas leak followed by small fire in industrial area near Vadodara port. Workers evacuated but fire spreading.',
    aiTriage: {
      severity: 'P2_high',
      category: 'rescue',
      extractedLocation: 'Vadodara Industrial Port area',
      triageNotes: 'Fire brigade + hazmat team required. Evacuate 500m radius.',
      triageConfidence: 0.91,
    },
    location: { lat: 22.3290, lng: 73.1650, landmark: 'Industrial Port' },
    status: 'in_progress',
    casualtyCount: 0,
    damageLevel: 'high',
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    incidentId: 'inc-005',
    incidentType: 'missing',
    rawDescription: 'Three children missing after flash flood in riverside area. Last seen near Mahi River bank at 9am.',
    aiTriage: {
      severity: 'P2_high',
      category: 'rescue',
      extractedLocation: 'Mahi River bank',
      triageNotes: 'Search & rescue team required. Drone surveillance recommended.',
      triageConfidence: 0.88,
    },
    location: { lat: 22.2950, lng: 73.2100, landmark: 'Mahi River bank' },
    status: 'new',
    casualtyCount: 3,
    damageLevel: 'high',
    createdAt: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    incidentId: 'inc-006',
    incidentType: 'shelter',
    rawDescription: 'Approximately 200 displaced residents sheltering in primary school. Food and water supply critically low.',
    aiTriage: {
      severity: 'P3_medium',
      category: 'shelter',
      extractedLocation: 'Government Primary School, Ward 7',
      triageNotes: 'Supply convoy required within 6 hours. Sanitation check needed.',
      triageConfidence: 0.95,
    },
    location: { lat: 22.3100, lng: 73.1750, landmark: 'Ward 7 Primary School' },
    status: 'triaged',
    casualtyCount: 0,
    damageLevel: 'medium',
    createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
  },
];

export const MOCK_RESOURCES = [
  {
    resourceId: 'res-001',
    name: 'NDRF Team Alpha',
    type: 'team',
    subType: 'ndrf',
    status: 'deployed',
    location: { lat: 22.3150, lng: 73.1880 },
    assignedIncidentIds: ['inc-002'],
    capacity: 20,
    currentLoad: 20,
  },
  {
    resourceId: 'res-002',
    name: 'Rescue Boat B7',
    type: 'vehicle',
    subType: 'boat',
    status: 'en_route',
    location: { lat: 22.3080, lng: 73.1830 },
    assignedIncidentIds: ['inc-001'],
    capacity: 12,
    currentLoad: 4,
  },
  {
    resourceId: 'res-003',
    name: 'Ambulance Unit 3',
    type: 'medical_unit',
    subType: 'ambulance',
    status: 'deployed',
    location: { lat: 22.3010, lng: 73.1930 },
    assignedIncidentIds: ['inc-003'],
    capacity: 2,
    currentLoad: 2,
  },
  {
    resourceId: 'res-004',
    name: 'Fire Brigade Delta',
    type: 'vehicle',
    subType: 'fire_brigade',
    status: 'deployed',
    location: { lat: 22.3285, lng: 73.1660 },
    assignedIncidentIds: ['inc-004'],
    capacity: 8,
    currentLoad: 8,
  },
  {
    resourceId: 'res-005',
    name: 'Supply Convoy Echo',
    type: 'vehicle',
    subType: 'supply_truck',
    status: 'available',
    location: { lat: 22.3200, lng: 73.1700 },
    assignedIncidentIds: [],
    capacity: 50,
    currentLoad: 0,
  },
  {
    resourceId: 'res-006',
    name: 'Medical Camp Foxtrot',
    type: 'medical_unit',
    subType: 'field_hospital',
    status: 'available',
    location: { lat: 22.3050, lng: 73.1800 },
    assignedIncidentIds: [],
    capacity: 100,
    currentLoad: 45,
  },
  {
    resourceId: 'res-007',
    name: 'Helicopter Unit H1',
    type: 'vehicle',
    subType: 'helicopter',
    status: 'available',
    location: { lat: 22.3300, lng: 73.2000 },
    assignedIncidentIds: [],
    capacity: 8,
    currentLoad: 0,
  },
];

export const SYSTEM_STATS = {
  totalIncidents: 6,
  critical: 3,
  highPriority: 2,
  resolved: 0,
  activeMeshNodes: 47,
  meshClusters: 3,
  pendingSync: 12,
  resourcesAvailable: 3,
  resourcesDeployed: 4,
  lastSyncAt: new Date(Date.now() - 2 * 60000).toISOString(),
};
